Repository wecode-bootcamp-korea/31-1st-MUZIMAKZI-frontend, pull requests merged in 2022-04, with the labels that each got.

#6 [31기 노규현] 공용 Nav 구현
  public/data/innerList.json
  public/images/nav/MUZI.png
  public/images/nav/MUZISIDE.png
  public/images/nav/searchIcon.png
  src/assets/login.png
  src/assets/shopping-bag.png
  src/assets/user.png
  src/components/nav/Nav.js
  src/components/nav/Nav.scss
  src/pages/Landing/Landing.js
  src/styles/variables.scss
Labels: Status: Accepted

#7 [31기 문혜성] 로그인, 회원가입 페이지 리뷰 반영 완료
  public/images/loginsignup/MUZI.png
  public/images/loginsignup/無知莫知.png
  src/Router.js
  src/assets/exit.png
  src/components/nav/Nav.js
  src/components/nav/Nav.scss
  src/pages/Landing/Landing.js
  src/pages/LoginSignup/Login/Login.js
  src/pages/LoginSignup/Login/Login.scss
  src/pages/LoginSignup/LoginSignup.js
  src/pages/LoginSignup/LoginSignup.scss
  src/pages/LoginSignup/Signup/Signup.js
  src/pages/LoginSignup/Signup/Signup.scss
  src/pages/LoginSignup/components/Button.js
  src/pages/LoginSignup/components/Button.scss
  src/pages/LoginSignup/components/Form.js
  src/pages/LoginSignup/components/Form.scss
  src/pages/LoginSignup/components/FormLayout.js
  src/pages/LoginSignup/components/FormLayout.scss
  src/pages/LoginSignup/components/Input.js
  src/pages/LoginSignup/components/input.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#13 [31기 노규현] 랜딩페이지 UI 구현 및 버튼,자동슬라이드 기능 구현 / 리뷰 반영 완료
  public/data/contentslist.json
  public/data/swiperItems.json
  public/images/landingpage/README.md
  public/images/landingpage/leftnext.png
  public/images/landingpage/rightnext.png
  public/images/landingpage/검정옷.jpg
  public/images/landingpage/도로1.jpg
  public/images/landingpage/도로2.jpg
  public/images/landingpage/무지책.jpg
  public/images/landingpage/무지호텔.jpg
  public/images/landingpage/바다1.jpg
  public/images/landingpage/바다2.jpg
  public/images/landingpage/바다3.jpg
  public/images/landingpage/붉은꽃.jpg
  public/images/landingpage/여러색옷.jpg
  public/images/landingpage/접어둔여러색옷.jpg
  public/images/landingpage/하얀꽃.jpg
  public/images/landingpage/흑백구름.jpg
  public/images/landingpage/흰구름.jpg
  public/images/landingpage/흰문.jpg
  public/images/landingpage/흰물품들.jpg
  public/images/landingpage/흰옷걸이.jpg
  public/images/landingpage/흰조명.jpg
  public/images/landingpage/흰침대.jpg
  src/Router.js
  src/pages/Landing/Landing.js
  src/pages/Landing/Landing.scss
  src/pages/Landing/LandingContents/Content.js
  src/pages/Landing/LandingContents/LandingContents.js
  src/pages/Landing/LandingContents/LandingContents.scss
  src/pages/Landing/Slider/Slider.js
  src/pages/Landing/Slider/SliderButton.js
  src/pages/Landing/Slider/SliderButton.scss
  src/pages/Landing/Slider/SwiperData.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#16 [31기 문혜성] fetch 함수 구조분해할당 버그 수정
  src/pages/LoginSignup/LoginSignup.js
  src/pages/LoginSignup/components/Button.js
  src/pages/LoginSignup/components/Form.js
Labels: Status: 리뷰 요청

#15 [31기 노규현] API 호출을 통한 Aside 구현, QueryString 을 통한 각 항목 url 연결 구현 / 수정리뷰 반영완료
  public/data/categorylist.json
  src/Router.js
  src/components/aside/Aside.js
  src/components/aside/Aside.scss
Labels: Status: 수정 요청

#17 [31기 노규현] Props children 적용하여 pagelayout 재구현
  src/ContentsWrapper/ContentsWrapper.js
  src/ContentsWrapper/ContentsWrapper.scss
  src/MainContainer/MainContainer.js
  src/MainContainer/MainContainer.scss
  src/Router.js
  src/components/aside/Aside.js
  src/components/nav/Nav.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#14 [31기 윤서영] list 페이지 UI 구현, 추가 기능
  public/data/MockData.json
  public/favicon.ico
  public/images/listpage/AAC07A0A_COL_525_130.jpg
  public/images/listpage/README.md
  public/images/listpage/btn_first_dim.gif
  public/images/listpage/btn_last_dim.gif
  public/images/listpage/btn_next_dim.gif
  public/images/listpage/btn_prev_dim.gif
  public/images/listpage/image1.jpg
  public/images/listpage/image10.jpg
  public/images/listpage/image2.jpg
  public/images/listpage/image3.jpg
  public/images/listpage/image4.jpg
  public/images/listpage/image5.jpg
  public/images/listpage/image6.jpg
  public/images/listpage/image7.jpg
  public/images/listpage/image8.jpg
  public/images/listpage/image9.jpg
  public/images/listpage/남성니트1.jpg
  public/images/listpage/남성니트10.jpg
  public/images/listpage/남성니트2.jpg
  public/images/listpage/남성니트3.jpg
  public/images/listpage/남성니트4.jpg
  public/images/listpage/남성니트5.jpg
  public/images/listpage/남성니트6.jpg
  public/images/listpage/남성니트7.jpg
  public/images/listpage/남성니트8.jpg
  public/images/listpage/남성니트9.jpg
  public/index.html
  src/pages/Labo/Labo.js
  src/pages/Labo/Labo.scss
  src/pages/List/ItemListComponents/ItemList.js
  src/pages/List/ItemListComponents/ItemList.scss
  src/pages/List/List.js
  src/pages/List/List.scss
  src/pages/List/SelectBoxComponents/selectBox.js
  src/pages/List/SelectBoxComponents/selectBox.scss
  src/pages/List/SelectTextComponents/SelectText.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#9 [31기 문혜성] Add: 장바구니 회원토큰에 따른 장바구니 목록, 삭제
  public/data/CartData.json
  public/images/cartpage/ABA19A2S_COL_375_80.jpeg
  public/images/cartpage/BBT17A2S_COL_01_80.jpeg
  public/images/cartpage/step1.gif
  src/components/nav/Nav.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/components/CartItemCell.js
  src/pages/Cart/components/CartItemCell.scss
  src/pages/LoginSignup/LoginSignup.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#21 [31기 윤서영] modify: branch이름 변경, womens page 연결
  public/images/detailpage/README.md
  public/images/detailpage/남성니트뒤1.jpg
  public/images/detailpage/남성니트뒤10.jpg
  public/images/detailpage/남성니트뒤2.jpg
  public/images/detailpage/남성니트뒤3.jpg
  public/images/detailpage/남성니트뒤4.jpg
  public/images/detailpage/남성니트뒤5.jpg
  public/images/detailpage/남성니트뒤6.jpg
  public/images/detailpage/남성니트뒤7.jpg
  public/images/detailpage/남성니트뒤8.jpg
  public/images/detailpage/남성니트뒤9.jpg
  src/components/aside/Aside.js
  src/components/nav/Nav.js
  src/pages/List/List.js
  src/pages/List/SelectBoxComponents/selectBox.js
  src/pages/List/SelectBoxComponents/selectBox.scss
  src/pages/Mens/Mens.js
Labels: Status: 리뷰 요청
